### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by Kanahiro** [Kanahiro/chiitiler#1]

**Comment by Kanahiro** [comment]
- try to run chiitiler on debian11
- debian11 needs some dependencies - https://github.com/maplibre/maplibre-native/tree/main/platform/linux
- linux/arm is difficult to build

**Comment by UncleWeeds** [comment]
I can take care of it

**Comment by Kanahiro** [comment]
solved by [df55c2c](https://github.com/Kanahiro/chiitiler/commit/df55c2c6f40206ef31b30a5cd21207f287d7da50)
